# Generated by Django 5.2.4 on 2025-07-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_student_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["full_name"]},
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("full_name", "group")},
        ),
    ]
